/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-gradient-to-br',
    'from-pink-100',
    'to-pink-200',
    'from-yellow-100', 
    'to-yellow-200',
    'from-green-100',
    'to-green-200',
    'from-purple-100',
    'to-purple-200',
    'from-blue-100',
    'to-blue-200',
    'from-amber-200',
    'from-teal-200',
    'from-gray-100',
    'to-gray-200',
    'bg-emerald-600',
    'hover:bg-emerald-700',
    'bg-emerald-50',
    'text-emerald-600',
    'text-emerald-700',
    'hover:text-emerald-700',
    'border-emerald-100',
    'from-emerald-50/60',
    'rounded-xl',
    'hover:shadow-lg',
    'transition-shadow',
    'text-6xl',
    'bg-yellow-100',
    'text-yellow-800',
    'bg-blue-100',
    'text-blue-800',
    'bg-green-100',
    'text-green-800',
    'bg-gray-100',
    'text-gray-800',
    'bg-red-100',
    'text-red-600',
    'bg-purple-100',
    'text-purple-600',
    'divide-y',
    'divide-gray-200',
    // Mobile-specific classes
    'touch-manipulation',
    'select-none',
    'safe-area-top',
    'safe-area-bottom',
    'safe-area-left',
    'safe-area-right',
    'h-safe-top',
    'h-safe-bottom',
    'w-safe-left',
    'w-safe-right',
    'pt-safe-top',
    'pb-safe-bottom',
    'pl-safe-left',
    'pr-safe-right',
    'min-h-[32px]',
    'min-h-[36px]',
    'min-h-[44px]',
    'min-h-[48px]',
    'min-h-[52px]',
    'min-w-[32px]',
    'min-w-[36px]',
    'min-w-[44px]',
    'min-w-[48px]',
    'min-w-[52px]'
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          50: '#F4EEDE',
          100: '#E8E4DB',
          200: '#D5CFC3',
          300: '#B7B2A7',
          400: '#98948B',
          500: '#7A766E',
          600: '#5C5952',
          700: '#3E3B37',
          800: '#1F2C4F',
          900: '#161F38',
          950: '#0B0F1A',
        },
        gray: {
          50: '#F4EEDE',
          100: '#E8E4DB',
          200: '#D5CFC3',
          300: '#B7B2A7',
          400: '#98948B',
          500: '#7A766E',
          600: '#5C5952',
          700: '#3E3B37',
          800: '#1F2C4F',
          900: '#161F38',
          950: '#0B0F1A',
        },
        emerald: {
          50: '#ECF8F2',
          100: '#D9F0E5',
          200: '#B3E1CC',
          300: '#8DD2B2',
          400: '#67C399',
          500: '#2E9E6D',
          600: '#1F6E4C',
          700: '#164F37',
          800: '#0F3626',
          900: '#082015',
        },
        amber: {
          50: '#FDF8E8',
          100: '#FBF0C9',
          200: '#F7E29B',
          300: '#F3D46D',
          400: '#EFC63F',
          500: '#E8A33D',
          600: '#C6821F',
          700: '#8F5E16',
          800: '#5C3D0E',
          900: '#3D2809',
        },
        teal: {
          50: '#ECF8F2',
          100: '#D9F0E5',
          200: '#B3E1CC',
          300: '#8DD2B2',
          400: '#67C399',
          500: '#2E9E6D',
          600: '#1F6E4C',
          700: '#164F37',
          800: '#0F3626',
          900: '#082015',
        },
        red: {
          50: '#FDF0EC',
          100: '#FADBD0',
          200: '#F5B7A1',
          300: '#EF9272',
          400: '#E96E43',
          500: '#C1502E',
          600: '#A34326',
          700: '#75311C',
          800: '#4A1F11',
          900: '#32140A',
        },
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      screens: {
        'xs': '475px',
        '3xl': '1600px',
      },
      fontFamily: {
        'sans': ['IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Inter', 'sans-serif'],
        'display': ['Bricolage Grotesque', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'strong': '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'fade-out': 'fadeOut 0.3s ease-in-out',
        'slide-in-up': 'slideInUp 0.3s ease-out',
        'slide-in-down': 'slideInDown 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-in',
        'bounce-gentle': 'bounceGentle 0.6s ease-in-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInDown: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
      },
      transitionTimingFunction: {
        'bounce-gentle': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [
    // Add custom utilities
    function({ addUtilities }) {
      const newUtilities = {
        '.touch-manipulation': {
          'touch-action': 'manipulation',
        },
        '.select-none': {
          '-webkit-user-select': 'none',
          '-moz-user-select': 'none',
          '-ms-user-select': 'none',
          'user-select': 'none',
        },
        '.safe-area-top': {
          'padding-top': 'env(safe-area-inset-top)',
        },
        '.safe-area-bottom': {
          'padding-bottom': 'env(safe-area-inset-bottom)',
        },
        '.safe-area-left': {
          'padding-left': 'env(safe-area-inset-left)',
        },
        '.safe-area-right': {
          'padding-right': 'env(safe-area-inset-right)',
        },
        '.h-safe-top': {
          'height': 'env(safe-area-inset-top)',
        },
        '.h-safe-bottom': {
          'height': 'env(safe-area-inset-bottom)',
        },
        '.w-safe-left': {
          'width': 'env(safe-area-inset-left)',
        },
        '.w-safe-right': {
          'width': 'env(safe-area-inset-right)',
        },
        '.pt-safe-top': {
          'padding-top': 'env(safe-area-inset-top)',
        },
        '.pb-safe-bottom': {
          'padding-bottom': 'env(safe-area-inset-bottom)',
        },
        '.pl-safe-left': {
          'padding-left': 'env(safe-area-inset-left)',
        },
        '.pr-safe-right': {
          'padding-right': 'env(safe-area-inset-right)',
        },
      }
      addUtilities(newUtilities)
    },
  ],
}
